ARG PG_MAJOR=15
FROM postgres:$PG_MAJOR
ARG PG_MAJOR

# COPY . /tmp/pgvector

RUN apt-get update && \
		apt-mark hold locales && \
		apt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR && \
        # mkdir /tmp/pgvector && \
		cd /tmp && \
        apt-get install -y git && \
        git clone https://github.com/pgvector/pgvector.git && \
		cd pgvector && \
		make clean && \
		make OPTFLAGS="" && \
		make install && \
		mkdir /usr/share/doc/pgvector && \
		cp LICENSE README.md /usr/share/doc/pgvector && \
		rm -r /tmp/pgvector && \
		apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR && \
		apt-get autoremove -y && \
		apt-mark unhold locales && \
		rm -rf /var/lib/apt/lists/*

# Run the rest of the commands as the `postgres` user created by the base image.
USER postgres

# Copy the initialization script
COPY db_init_script.sql /docker-entrypoint-initdb.d/
