version: '3.1'

services:
  postgres:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-postgresql
    image: project-lynk-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
