# Use the official PostgreSQL image as a base
FROM postgres:latest

# Set the locale
ENV LANG C.UTF-8

# Install pgvector
RUN apt-get update && \
    apt-get install -y build-essential postgresql-server-dev-all && \
    apt-get clean && \
    apt-get install -y git && \
    apt-get install -y postgresql-server-dev-15 &&\
    git clone --branch v0.5.0 https://github.com/pgvector/pgvector.git &&\
    cd pgvector && \
    make clean && \
    make install && \
    rm -rf /var/lib/apt/lists/*

# Run the rest of the commands as the `postgres` user created by the base image.
USER postgres

# Copy the initialization script
COPY db_init_script.sql /docker-entrypoint-initdb.d/
